branch-defaults:
  dev:
    environment: udagram-zucchell-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-zucchell-dev
  branch: null
  default_ec2_keyname: udagram-zucchelli-dev
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
